apiVersion: v1
kind: Service
metadata:
  name: openeco-web
  labels:
    app: openeco-web
spec:
  selector:
    app: openeco-web
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP


